name: 'The Docker CLI'
description: 'GitHub Action with docker cli'
author: 'Serhiy Mytrovtsiy <mitrovtsiy@ukr.net>'
branding:
  icon: 'box'
  color: 'blue'
inputs:
  NAME:
    description: 'Docker image (if not the same as repo)'
    required: false
  TAG:
    description: 'Docker tag (if want to specify tag)'
    required: false
runs:
  using: 'docker'
  image: './cli/Dockerfile'
