name: 'The Docker CLI'
description: 'GitHub Action with docker cli'
author: 'Serhiy Mytrovtsiy <mitrovtsiy@ukr.net>'
branding:
  icon: 'box'
  color: 'blue'
inputs:
  NAME:
    description: 'Docker image (if not the same as repo)'
  TAG:
    description: 'Docker tag (if want to specify tag)'
  DOCKER_USERNAME:
    description: 'Docker username'
  DOCKER_PASSWORD:
    description: 'Docker password'
  DOCKER_REGISTRY_URL:
    description: 'Docker registry url'
runs:
  using: 'docker'
  image: './cli/Dockerfile'
